name: CI/CD MT Challenge

on:
  [workflow_dispatch, push]

#concurrency: cicd-ml-challenge-${{ github.ref }}

env:
  TRIGGER_FILES: "airflow/dags*|.github/workflows/"

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        echo "pylint **/*.py"

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt
      
      - name: pytest
        run: |
          echo "pytest"
